### ISSUE TITLE
Delete `release/6.0` branch

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/xharness#1328]
### Description

.NET 6 reached EOL: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#:~:text=For%20example%2C%20.NET%206%20was,which%20is%20November%2012%2C%202024.

With that, we don't need to maintain the release/6.0 branch anymore.

### Tasks
- [x] Remove darc subscriptions for release/6.0 branch
- [x] Add a tag marking the point of deletion (for potential revival)
- [x] Delete the branch
- [x] Remove the branch from tracking in Component Governance: https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-xharness?_a=settings&view=trackedBranches

**Comment by ivanpovazan** [comment]
@akoeplinger did I miss something in the list of tasks?

**Comment by akoeplinger** [comment]
I added CG to the list, looks good to me otherwise.

**Comment by ivanpovazan** [comment]
This is now completed. 
Tag: https://github.com/dotnet/xharness/releases/tag/6.0.0-EOL
